"use strict";
exports.__esModule = true;
var Express = require("express");
var App = Express();
var equipamento_1 = require("./model/equipamento");
var cargoRouter = require("./routes/cargoRoute");
var funcionarioRouter = require("./routes/funcionarioRoute");
var loginRouter = require("./routes/loginRoute");
var equipamentoRouter = require("./routes/equipamentoRoute");
var manutencaoRouter = require("./routes/manutencaoRoute");
var pecaRouter = require("./routes/pecaRoute");
var qrcodeRouter = require("./routes/qrcodeRoute");
var setorRouter = require("./routes/setorRoute");
App.use(Express.json());
App.use(Express.urlencoded({ extended: true }));
App.use(Express.static(__dirname));
App.use(cargoRouter);
App.use(funcionarioRouter);
App.use(loginRouter);
App.use(equipamentoRouter);
App.use(manutencaoRouter);
App.use(pecaRouter);
App.use(qrcodeRouter);
App.use(setorRouter);
App.listen(3000);
console.log("Executando...\n");
var notebook = new equipamento_1.Equipamento("1", "1", "1", "1", "1", "1", "1", "1", "1");
console.log(notebook);
