"use strict";
exports.__esModule = true;
var Express = require("express");
var Mongoose = require("mongoose");
var dotenv = require("dotenv");
dotenv.config();
var App = Express();
var cargoRouter = require("./routes/cargoRoute");
var funcionarioRouter = require("./routes/funcionarioRoute");
var loginRouter = require("./routes/loginRoute");
var equipamentoRouter = require("./routes/equipamentoRoute");
var manutencaoRouter = require("./routes/manutencaoRoute");
var pecaRouter = require("./routes/pecaRoute");
var qrcodeRouter = require("./routes/qrcodeRoute");
var setorRouter = require("./routes/setorRoute");
Mongoose.connect(process.env.LOCAL_DB_CONN_STRING);
App.use(Express.json());
App.use(Express.urlencoded({ extended: true }));
App.use(Express.static(__dirname));
App.use(cargoRouter);
App.use(funcionarioRouter);
App.use(loginRouter);
App.use(equipamentoRouter);
App.use(manutencaoRouter);
App.use(pecaRouter);
App.use(qrcodeRouter);
App.use(setorRouter);
App.listen(3000);
console.log("Executando...\n");
