"use strict";
var Express = require("express");
var Router = Express.Router();
var equipamentoController_1 = require("../controller/equipamentoController");
var loginController_1 = require("../controller/loginController");
Router.get("/equipamento", loginController_1.autenticarJWT, equipamentoController_1.listarEquipamento);
Router.post("/equipamento", loginController_1.autenticarJWT, equipamentoController_1.inserirEquipamento);
Router.put("/equipamento/:id", loginController_1.autenticarJWT, equipamentoController_1.alterarEquipamento);
Router["delete"]("/equipamento/:id", loginController_1.autenticarJWT, equipamentoController_1.removerEquipamento);
Router.get("/test/equipamento", equipamentoController_1.listarEquipamento);
Router.post("/test/equipamento", equipamentoController_1.inserirEquipamento);
Router.put("/test/equipamento/:id", equipamentoController_1.alterarEquipamento);
Router["delete"]("/test/equipamento/:id", equipamentoController_1.removerEquipamento);
module.exports = Router;
