"use strict";
var Express = require("express");
var pecaController_1 = require("../controller/pecaController");
var loginController_1 = require("../controller/loginController");
var Router = Express.Router();
Router.get("/peca", loginController_1.autenticarJWT, pecaController_1.listarPeca);
Router.post("/peca", loginController_1.autenticarJWT, pecaController_1.inserirPeca);
Router.put("/peca/:id", loginController_1.autenticarJWT, pecaController_1.alterarPeca);
Router["delete"]("/peca/:id", loginController_1.autenticarJWT, pecaController_1.removerPeca);
module.exports = Router;
