"use strict";
var Express = require("express");
var qrcodeController_1 = require("../controller/qrcodeController");
var loginController_1 = require("../controller/loginController");
var Router = Express.Router();
Router.get("/qrcode/teste", loginController_1.autenticarJWT, qrcodeController_1.testeGoogle);
Router.post("/qrcode/string", loginController_1.autenticarJWT, qrcodeController_1.toString);
Router.post("/qrcode/dataurl", loginController_1.autenticarJWT, qrcodeController_1.toDataURL);
Router.post("/qrcode/file", loginController_1.autenticarJWT, qrcodeController_1.toFile);
Router.get("/qrcode/consulta", loginController_1.autenticarJWT, qrcodeController_1.consultaCodigo);
Router.post("/qrcode", loginController_1.autenticarJWT, qrcodeController_1.inserirQrcode);
Router.get("/qrcode", loginController_1.autenticarJWT, qrcodeController_1.listarQrcode);
Router.put("/qrcode/:id", loginController_1.autenticarJWT, qrcodeController_1.alterarQrcode);
Router["delete"]("/qrcode/:id", loginController_1.autenticarJWT, qrcodeController_1.removerQrcode);
module.exports = Router;
