"use strict";
var Express = require("express");
var setorController_1 = require("../controller/setorController");
var loginController_1 = require("../controller/loginController");
var Router = Express.Router();
Router.get("/setor", loginController_1.autenticarJWT, setorController_1.listarSetor);
Router.post("/setor", loginController_1.autenticarJWT, setorController_1.inserirSetor);
Router.put("/setor/:id", loginController_1.autenticarJWT, setorController_1.alterarSetor);
Router["delete"]("/setor/:id", loginController_1.autenticarJWT, setorController_1.removerSetor);
module.exports = Router;
